---
title: "Site KRI Report"
author: "[gsm.kri](https://gilead-public.github.io/gsm.kri) Example"
description: "Example of a Site KRI Report generated using standard KRIs in gsm.kri"
index: 1
date: "`r format(Sys.time(), '%B %d, %Y %H:%M:%S %Z')`"
output:
  html_document:
    mathjax: null
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    css: styles.css
---

# Set Up

This page provides a sample Site KRI Report generated using the standard KRIs included in the `gsm.kri` package. Expand the "Setup" section below to see the code used to generate the report. Or scroll down for the standard KRI report output.

<details>
<summary>Setup</summary>

```{r}
# Load libraries
library(gsm.core)
library(gsm.kri)
library(here)

## Retired metric: inactive, with results in earlier snapshots only.
## The example data have none, so one is copied from the Adverse Event Rate.
dfMetrics <- gsm.core::reportingMetrics %>%
  dplyr::filter(MetricID == "Analysis_kri0001") %>%
  dplyr::mutate(
    MetricID = "Analysis_kri9999",
    Metric = "Retired Metric",
    Abbreviation = "RET",
    Active = FALSE
  ) %>%
  dplyr::bind_rows(gsm.core::reportingMetrics, .)
dfResults <- gsm.core::reportingResults %>%
  dplyr::filter(
    MetricID == "Analysis_kri0001",
    SnapshotDate < max(SnapshotDate)
  ) %>%
  dplyr::mutate(MetricID = "Analysis_kri9999") %>%
  dplyr::bind_rows(gsm.core::reportingResults, .)

## Site Report
lCharts <- gsm.kri::MakeCharts(
  dfResults = dfResults,
  dfGroups = gsm.core::reportingGroups,
  dfMetrics = dfMetrics,
  dfBounds = gsm.core::reportingBounds
)
```

</details>

# Report

```{r, echo=FALSE, results='asis'}
## Render example report inline using knit_child
child_env <- list2env(
  list(
    params = list(
      lCharts = lCharts,
      # All snapshots: the retired metric has no results in the latest one.
      dfResults = dfResults,
      dfGroups = gsm.core::reportingGroups,
      dfMetrics = dfMetrics
    )
  ),
  parent = environment()
)
report_kri <- knitr::knit_child(
  system.file("report", "Report_KRI.Rmd", package = "gsm.kri"),
  envir = child_env,
  quiet = TRUE
)
cat(report_kri, sep = "\n")
```